version: "3"

services:
  mysql:
    container_name: mysql
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "tekever-database"
      MYSQL_USER: "tekever"
      MYSQL_PASSWORD: "password"
      MYSQL_PORT: "3306:3306"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  db:
