version: "3"

services:
  mysql:
    container_name: mysql
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "tekever-database"
      MYSQL_USER: "tekever"
      MYSQL_PASSWORD: "password"
      MYSQL_PORT: "3306:3306"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  tekever-code-challenge:
    container_name: tekever-api
    image: "adrianonevesps/tekever:latest"
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: hml
      PORT: 9000
      KEYCLOAK_URL: https://tekever-keycloak.labsmaisdigital.com.br
      KEYCLOAK_CLIENTID: tekever-client
      KEYCLOAK_CLIENT_SECRET: TTmRJZvRSfPN408cq1D8aBvMVyXNQHZX
      KEYCLOAK_MASTER_USERNAME: admin
      KEYCLOAK_MASTER_PASSWORD: tekever
      KEYCLOAK_MASTER_CLIENT_ID: admin-cli
      KEYCLOAK_REALM: tekever
      KEYCLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvW/DPY8s/kGfToR/YNc/50GxPWYmUZkjGy719XVFkGL42H3eXl7iBiXRRtFyhSuIe8w/knnqxJUylD5a5xeAWTDsY7GcCQLZDQ+QbvoheEjmmeibgW1TRpMexRuE+074dDvgYjl8sntwOBre77jdOzO4D0qteJ2PzwyaowVzJbK3NPRJrHSvZDtLUoB23nBn75zq8JntuWNGSk7Zddf5EeKljvbJe9V84UFTnyU/2PUg0r819TpNI4QMCe3rylY//g01PNvPOve267ahrLp7McH9Rl9roKPx7OqaRx6TszX8VZqXQAyDpXBOPeXuvRwkkWrTSn2HdsbJ1XBqvGSVFQIDAQAB
      DATABASE_URL: "mysql://root:root@mysql:3306/tekever-database?schema=public"
      REDIS_HOST: redis
volumes:
  redis:
    driver: local
  db:
