version: "3"

services:
  tekever-code-challenge:
    container_name: tekever-api
    image: "adrianonevesps/tekever:latest"
    ports:
      - "9000:9000"
    env_file: .env
    environment:
      NODE_ENV: hml
      PORT: 9000
      KEYCLOAK_URL: https://keycloak-hml.lbsdigital.com.br
      KEYCLOAK_CLIENTID: teste-client
      KEYCLOAK_CLIENT_SECRET: n5yrblbDemIJuPpifH1zn01nMk0RwCAP
      KEYCLOAK_MASTER_USERNAME: admin
      KEYCLOAK_MASTER_PASSWORD: mu26NUzdKUUP1OdU
      KEYCLOAK_MASTER_CLIENT_ID: admin-cli
      KEYCLOAK_REALM: Teste
      KEYCLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6f8bbd5yXYMDyDWAYVeCVjzWSr+E0wYAWeBCW+jxvGMeP4THgk1dw8CACls1Gd1m7Wr2O4vy89ENmTJIbOg3Xg2Et6WAHqXQ/ffuCEHX5emHwQnp+GrbcfEVZUZK08bwlt9ImN1Y+xzcUqV4UD1oIy6IZt6qOWuUAx29vL1//rWU8/MqwnjaCpi+QssQl2T9N0UiuvknVN5XevZ9MtwK6OHR5+jUm7a4cO2MKXQx5VIUKBhi0mTvrTIv3fcuEUeEnboZ7M6JQVMKM4kmCnPByTqm/9lfdHg3fA5btdEQCro6WEx7RpNhttzmo6Skt9PjsRCYEevR56vGZyNitM7WswIDAQAB
      DATABASE_URL: "mysql://root:root@localhost:3906/tekever-database?schema=public"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "iveco-backend"
      MYSQL_USER: "boilerplate"
      MYSQL_PASSWORD: "password"
      MYSQL_PORT: "3906:3306"
      REDIS_PORT: 6379
