version: "3"

services:
  mysql:
    container_name: mysql
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "tekever-database"
      MYSQL_USER: "tekever"
      MYSQL_PASSWORD: "password"
      MYSQL_PORT: "3306:3306"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  tekever-code-challenge:
    container_name: tekever-api
    image: "adrianonevesps/tekever:v4"
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: hml
      PORT: 9000
      KEYCLOAK_URL: https://keycloak-hml.lbsdigital.com.br
      KEYCLOAK_CLIENTID: teste-client
      KEYCLOAK_CLIENT_SECRET: n5yrblbDemIJuPpifH1zn01nMk0RwCAP
      KEYCLOAK_MASTER_USERNAME: admin
      KEYCLOAK_MASTER_PASSWORD: mu26NUzdKUUP1OdU
      KEYCLOAK_MASTER_CLIENT_ID: admin-cli
      KEYCLOAK_REALM: Teste
      KEYCLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6f8bbd5yXYMDyDWAYVeCVjzWSr+E0wYAWeBCW+jxvGMeP4THgk1dw8CACls1Gd1m7Wr2O4vy89ENmTJIbOg3Xg2Et6WAHqXQ/ffuCEHX5emHwQnp+GrbcfEVZUZK08bwlt9ImN1Y+xzcUqV4UD1oIy6IZt6qOWuUAx29vL1//rWU8/MqwnjaCpi+QssQl2T9N0UiuvknVN5XevZ9MtwK6OHR5+jUm7a4cO2MKXQx5VIUKBhi0mTvrTIv3fcuEUeEnboZ7M6JQVMKM4kmCnPByTqm/9lfdHg3fA5btdEQCro6WEx7RpNhttzmo6Skt9PjsRCYEevR56vGZyNitM7WswIDAQAB
      DATABASE_URL: "mysql://root:root@mysql:3306/tekever-database?schema=public"
volumes:
  redis:
    driver: local
  db:
