name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.6.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: touch .env
      - run: |
          cat <<EOF > .env
          ${{ vars.ENV_FILE_VAR }}
          EOF
      - run: ls -la
      - run: cat .env
      - run: yarn
      - run: yarn test
